//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime SerchDate { get; set; }
        public double EstimatedDiameter { get; set; }
        public string IsPotentiallyHazardousAsteroid { get; set; }
    }
}
