//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public double mass { get; set; }
        public double TrackRadius { get; set; }
        public double DurationOfRoute { get; set; }
        public double TrackInclination { get; set; }
        public double Diameter { get; set; }
        public double Eccentricity { get; set; }
        public double DayLength { get; set; }
        public int Moons { get; set; }
        public int PlanetaryRings { get; set; }
        public int Atmosphere { get; set; }
        public string ProfilePictureURL { get; set; }
    }
}
